version: 2
updates:

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    target-branch: "develop"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"

