name: Build Arcora Archetype
on:
  push:
    branches:
      - main
      - prerelease
jobs:
  build:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 10
        uses: actions/setup-node@v4
        with:
          node-version: '10'
      - name: Add Gulp
        run: npm install -g gulp-cli
      - name: Install dependencies
        run: npm install
      - name: Create ui-bundle.zip
        run: SOURCEMAPS=true gulp bundle
      
      - name: Create a Release
        id: create_release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "Release v0.${{ github.run_number }}"
          tag: v0.${{ github.run_number }}
          prerelease: true
      # - name: Upload asset to release
      #   uses: csexton/release-asset-action@v3
      #   with:
      #     file: build/ui-bundle.zip
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     release-url: ${{ steps.create_release.outputs.upload_url }}
      - name: "Upload asset to release"
        uses: SierraSoftworks/gh-releases@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: 'true'
          files: |
            build/ui-bundle.zip


